#############################################################################
# Generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#  Jul 20, 2022 12:59:46 AM +0700  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m53" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 824x504+267+122
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list disabled $vTcl(actual_gui_bg) selected $vTcl(complement_color)]
    ttk::notebook $top.tNo48 \
        -width 804 -height 455 -takefocus {} 
    vTcl:DefineAlias "$top.tNo48" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.tNo48.t0 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t0" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo48 add $top.tNo48.t0 \
        -padding 0 -sticky nsew -state normal -text {Trang chủ} -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo48.t0
    button $site_4_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Import 
    vTcl:DefineAlias "$site_4_0.but49" "btnImport" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_4_0.scr52 \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$site_4_0.scr52" "Scrolledtreeview1" vTcl:WidgetProc "Toplevel1" 1

        $base.tNo48.t0.scr52.01 configure -columns Col1 -height 4
        $base.tNo48.t0.scr52.01 configure -columns {Col1}
        $base.tNo48.t0.scr52.01 heading #0 -text {Tree}
        $base.tNo48.t0.scr52.01 heading #0 -anchor center
        $base.tNo48.t0.scr52.01 column #0 -width 389
        $base.tNo48.t0.scr52.01 column #0 -minwidth 20
        $base.tNo48.t0.scr52.01 column #0 -stretch 1
        $base.tNo48.t0.scr52.01 column #0 -anchor w
        $base.tNo48.t0.scr52.01 heading Col1 -text {Col1}
        $base.tNo48.t0.scr52.01 heading Col1 -anchor center
        $base.tNo48.t0.scr52.01 column Col1 -width 390
        $base.tNo48.t0.scr52.01 column Col1 -minwidth 20
        $base.tNo48.t0.scr52.01 column Col1 -stretch 1
        $base.tNo48.t0.scr52.01 column Col1 -anchor w
    button $site_4_0.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Upload 
    vTcl:DefineAlias "$site_4_0.but54" "btnUpload" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Get Cookies} 
    vTcl:DefineAlias "$site_4_0.but46" "btnGetCookies2" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.but49 \
        -in $site_4_0 -x 0 -relx 0.017 -y 0 -rely 0.882 -width 107 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.scr52 \
        -in $site_4_0 -x 0 -y 0 -rely 0.021 -width 0 -relwidth 0.998 \
        -height 0 -relheight 0.816 -anchor nw -bordermode ignore 
    place $site_4_0.but54 \
        -in $site_4_0 -x 0 -relx 0.239 -y 0 -rely 0.882 -width 107 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but46 \
        -in $site_4_0 -x 0 -relx 0.45 -y 0 -rely 0.881 -width 107 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo48.t1 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t1" "TNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo48 add $top.tNo48.t1 \
        -padding 0 -sticky nsew -state normal -text {Cài đặt} -image {} \
        -compound left -underline -1 
    set site_4_1  $top.tNo48.t1
    entry $site_4_1.ent48 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 74 
    vTcl:DefineAlias "$site_4_1.ent48" "txtSoLuong" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_1.ent49 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 74 
    vTcl:DefineAlias "$site_4_1.ent49" "txtSoVideoToiDa" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_1.ent53 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 274 
    vTcl:DefineAlias "$site_4_1.ent53" "txtKeyactive" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_4_1.che46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Bình luận và ghim} -variable checkCommentGhim 
    vTcl:DefineAlias "$site_4_1.che46" "check1" vTcl:WidgetProc "Toplevel1" 1
    message $site_4_1.mes48 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -padx 1 -pady 1 -text {Số luồng} -width 70 
    vTcl:DefineAlias "$site_4_1.mes48" "Message1" vTcl:WidgetProc "Toplevel1" 1
    message $site_4_1.mes49 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -padx 1 -pady 1 -text {Số video tối đa} -width 100 
    vTcl:DefineAlias "$site_4_1.mes49" "Message2" vTcl:WidgetProc "Toplevel1" 1
    message $site_4_1.mes50 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -padx 1 -pady 1 -text {Key kích hoạt} -width 91 
    vTcl:DefineAlias "$site_4_1.mes50" "Message3" vTcl:WidgetProc "Toplevel1" 1
    message $site_4_1.mes46 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -padx 1 -pady 1 -text Proxy -width 50 
    vTcl:DefineAlias "$site_4_1.mes46" "Message3_1" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_1.tCo48 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_4_1.tCo48" "comboProxy" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_1.ent48 \
        -in $site_4_1 -x 0 -relx 0.187 -y 0 -rely 0.024 -width 74 -relwidth 0 \
        -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.ent49 \
        -in $site_4_1 -x 0 -relx 0.187 -y 0 -rely 0.072 -width 74 -relwidth 0 \
        -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.ent53 \
        -in $site_4_1 -x 0 -relx 0.187 -y 0 -rely 0.126 -width 274 \
        -relwidth 0 -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.che46 \
        -in $site_4_1 -x 0 -relx 0.013 -y 0 -rely 0.186 -width 0 \
        -relwidth 0.164 -height 0 -relheight 0.058 -anchor nw \
        -bordermode ignore 
    place $site_4_1.mes48 \
        -in $site_4_1 -x 0 -y 0 -rely 0.023 -width 0 -relwidth 0.088 \
        -height 0 -relheight 0.044 -anchor nw -bordermode ignore 
    place $site_4_1.mes49 \
        -in $site_4_1 -x 0 -y 0 -rely 0.075 -width 0 -relwidth 0.12 -height 0 \
        -relheight 0.044 -anchor nw -bordermode ignore 
    place $site_4_1.mes50 \
        -in $site_4_1 -x 0 -y 0 -rely 0.128 -width 0 -relwidth 0.113 \
        -height 0 -relheight 0.044 -anchor nw -bordermode ignore 
    place $site_4_1.mes46 \
        -in $site_4_1 -x 0 -y 0 -rely 0.256 -width 0 -relwidth 0.063 \
        -height 0 -relheight 0.044 -anchor nw -bordermode ignore 
    place $site_4_1.tCo48 \
        -in $site_4_1 -x 0 -relx 0.188 -y 0 -rely 0.256 -width 0 \
        -relwidth 0.179 -height 0 -relheight 0.049 -anchor nw \
        -bordermode ignore 
    frame $top.tNo48.t2 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t2" "TNotebook1_t3" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo48 add $top.tNo48.t2 \
        -padding 0 -sticky nsew -state normal -text Log -image {} \
        -compound left -underline -1 
    set site_4_2  $top.tNo48.t2
    text $site_4_2.tex61 \
        -background white -font TkTextFont -foreground black -height 364 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 584 -wrap word 
    $site_4_2.tex61 configure -font "TkTextFont"
    $site_4_2.tex61 insert end text
    vTcl:DefineAlias "$site_4_2.tex61" "txtLog" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_2.tex61 \
        -in $site_4_2 -x 0 -y 0 -rely 0.027 -width 0 -relwidth 0.995 \
        -height 0 -relheight 0.971 -anchor nw -bordermode ignore 
    menu $top.m53 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    entry $top.ent56 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 394 
    vTcl:DefineAlias "$top.ent56" "txtStatus" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent57 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 404 
    vTcl:DefineAlias "$top.ent57" "txtHsd" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo48 \
        -in $top -x 0 -relx 0.011 -y 0 -rely 0.02 -width 0 -relwidth 0.976 \
        -height 0 -relheight 0.903 -anchor nw -bordermode ignore 
    place $top.ent56 \
        -in $top -x 0 -relx 0.012 -y 0 -rely 0.933 -width 394 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent57 \
        -in $top -x 0 -relx 0.498 -y 0 -rely 0.933 -width 404 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

